### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by ghost** [maxoodf/russian_news_corpus#3]
Do you have a list of sources that this corpus comes from? Like specific news outlets, article titles, dates, etc...
I would like to use your corpus for a school project.

Thank you

**Comment by maxoodf** [comment]
Sources: 
 http://echo.msk.ru
 http://izvestia.ru
 http://lenta.ru
 http://newsru.com
 http://regnum.ru
 http://rg.ru
 http://ria.ru
 http://tass.ru
 http://utro.ru
 http://vz.ru
 http://www.1tv.ru
 http://www.aif.ru
 http://www.fontanka.ru
 http://www.gazeta.ru
 http://www.interfax.ru
 http://www.kommersant.ru
 http://www.kp.ru
 http://www.mk.ru
 http://www.newizv.ru
 http://www.ng.ru
 http://www.novayagazeta.ru
 http://www.ntv.ru
 http://www.pravda.ru
 http://www.rbc.ru
 http://www.rosbalt.ru
 http://www.vedomosti.ru
 http://www.vesti.ru

**Comment by ghost** [comment]
Do you know of any russian news corpus that has news articles from 2019-2020?
